### ISSUE TITLE
plugin doesn't work anymore after MM update

### ISSUE THREAD

**Issue by isAAAc** [MatthewDorner/mattermost-plugin-chess#21]
Hello, 
the plugin doesn't work anymore since i upgraded MM, 

- on an already existing game, when i play, the next play isn't updated onto the game
- on a fresh game, no link to the board in the new dedicated chan

```
Mattermost Version: 5.36.1
Database Schema Version: 5.36.1
Database: mysql

Chess (com.matthewdorner.mattermost-plugin-chess - 1.0.0)
```
am i alone to encounter this issue ?

i already tried to disable/re-enable the plugin without any success

thx for you work and for your help

EDIT: i have exactly the same issue on a second server, same versions

**Comment by MatthewDorner** [comment]
OK, I'll look into it.

**Comment by MatthewDorner** [comment]
I think I figured it out, has to do with `mattermost-redux` dependency, I will get a fix & new release soon.

**Comment by isAAAc** [comment]
thx a lot for your investigation and your work ;)

**Comment by MatthewDorner** [comment]
You installed from the plugin bundle at https://github.com/MatthewDorner/mattermost-plugin-chess/releases/download/v1.0.0/com.matthewdorner.mattermost-plugin-chess-1.0.0.tar.gz, I assume? That's the only one I ever released, I just want to check that you installed using that rather than building the plugin yourself from the source code?

**Comment by MatthewDorner** [comment]
Can you try the new v1.1.0 release? https://github.com/MatthewDorner/mattermost-plugin-chess/releases/download/v1.1.0/com.matthewdorner.mattermost-plugin-chess-1.1.0.tar.gz. Should be fixed.

**Comment by isAAAc** [comment]
hello @MatthewDorner ;)
sorry for my late answer, 
as far as i can remember yes, i used the tarball

**Comment by MatthewDorner** [comment]
Ok, please let me know if the new version fixed it for you.

**Comment by isAAAc** [comment]
yes it works perfectly <3 
thx a lot ;)
this issue can be closed (on my side)

**Comment by isAAAc** [comment]
update of mattermost, 
the issue is back :/

Mattermost Version: 5.37.0
Database Schema Version: 5.37.0
Database: mysql

looks like the plugin is back on old version oO
Chess (com.matthewdorner.mattermost-plugin-chess - 1.0.0)

EDIT: perhaps mattermost do a git action on plugin folders during the update ? so if the new release is not in upstream, there is a rollback to the old version wich is in upstream ?

**Comment by MatthewDorner** [comment]
That's odd. Can you remove the plugin and install the new version again? The plugin bundle is only distributed as a release artifact from this GitHub repo (which is what I linked you to and what the readme links to).

I don't think Mattermost is re-downloading the old one during the upgrade (it doesn't even know where the bundle tar.gz file is from, it's just a file you downloaded), more likely something with caching or maybe the new one didn't overwrite the old one completely? I recall something about the bundles you install getting cached in the database, so that might have something to do with it.

Any case, it seems the issue with the plugin itself has been solved in the new release.

**Comment by isAAAc** [comment]
> the issue with the plugin itself has been solved in the new release

yes it is ;)

i only need to reinstall the last plugin version each time MM is upgrading, and then it works back.

**Comment by MatthewDorner** [comment]
Might be an issue with `mattermost-server`, maybe there is a bug with installing a new version of a plugin over an old one and then upgrading the server. Or maybe I left an old version number in my code somewhere, that could have something to do with it using the cached version? But I'm pretty sure I updated it correctly, anyway I'll look at it maybe make an issue in server if I think it's a bug.

**Comment by isAAAc** [comment]
still same bug on the last upgrade of the server

**Comment by ap0calypse** [comment]
Hi,
I recently made an upgrade to mm 6.3.2 and the chess plugin doesn't seem to work anymore. Could you tell me if that is a known issue?

**Comment by Roy-Orbison** [comment]
@ap0calypse It could be a different issue, now. I'm seeing this in the console of the Mattermost page when opening a game board:
```none
Uncaught ReferenceError: $ is not defined
    at I (com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:28:2949)
    at u (com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:28:13652)
    at com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:310:59432
I @ com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:28
u @ com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:28
(anonymous) @ com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:310
requestAnimationFrame (async)
componentDidUpdate @ com.matthewdorner.mattermost-plugin-chess_675ad83a3d6b93e1_bundle.js:310
ss @ react-dom.production.min.js:212
pu @ react-dom.production.min.js:255
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yn @ react-dom.production.min.js:122
gu @ react-dom.production.min.js:248
ou @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Yn @ react-dom.production.min.js:122
Qn @ react-dom.production.min.js:123
Vn @ react-dom.production.min.js:122
R @ react-dom.production.min.js:287
Vt @ react-dom.production.min.js:68
```
But if I type `$` directly into the console to evaluate it, it shows as a function, but it's all obfuscated code so I don't know what's going on.

**Comment by ap0calypse** [comment]
hi @Roy-Orbison :wave: 
what version of mattermost are you running if I might ask? If I invite someone to chess on this version I am running, I see the following: 
![image](https://user-images.githubusercontent.com/106821/153457249-0359144d-fa35-4b11-ad01-39954594ea7c.png)

... just looks empty. not sure where to go at this point.

EDIT: I also get the almost same error on console:
![image](https://user-images.githubusercontent.com/106821/153491170-ba99b84a-a694-4683-8159-cee5827a2628.png)

**Comment by Roy-Orbison** [comment]
@ap0calypse v6.3.3. It looks like it could be a simple error, referencing a function in the wrong scope, or loading something in the wrong order. Not something @MatthewDorner did, but Mattermost changing the environment. We'll just have to be patient.

**Comment by MatthewDorner** [comment]
I'll give it another look. This is probably something different than the original issue in this thread but a similar breaking due to server (most likely mattermost-webapp) update.

**Comment by MatthewDorner** [comment]
ok, I reproduced issue using the most recent server and webapp repos in a dev environment

**Comment by MatthewDorner** [comment]
It's because they removed jQuery lol

**Comment by Roy-Orbison** [comment]
I did think that might be it. The `$` global was missing the usual jQuery properties.

**Comment by MatthewDorner** [comment]
I'll just load jQuery from the plugin and make a new release.

**Comment by ap0calypse** [comment]
lol, :+1:

**Comment by MatthewDorner** [comment]
I just published `v1.1.1` release, can you confirm if this fixes the problem?

**Comment by aptrn** [comment]
I just tried downloading v1.1.1 and overwriting old plugin, it seems to work! 😄 
(and castling works too!)

**Comment by Roy-Orbison** [comment]
Thanks for repairing it, @MatthewDorner.

I notice that the `main.js` file is nearly a megabyte. Would you consider trying the [Closure Compiler][0] on `AGGRESSIVE_BUNDLE` level to prune away the unused code? It could significantly lighten your plugin.

[0]: https://github.com/webpack-contrib/closure-webpack-plugin

**Comment by MatthewDorner** [comment]
@Roy-Orbison I'll try it

**Comment by ap0calypse** [comment]
thanks @MatthewDorner, problem is fixed and chess is working again :+1:

**Comment by MatthewDorner** [comment]
@Roy-Orbison Couldn't get the compiler to work, but was able to reduce bundle size by about half by other means. Released v1.1.2. 

Closing this, if it breaks again we can start a new Issue.
